name: Publish on Docker Hub and Deploy

on:
    release:
        types: [published]
    # Запуск только при публиковании нового релиза

    # Можем запускать вручную из Actions tab
    workflow_dispatch:

jobs:
    run_tests:
        runs-on: [ubuntu-latest]
        steps:
            # Чекаутим код
            - uses: actions/checkout@v2
            - name: Install packages
              run: npm i
            - name: Make dist
              run: npm run build
    #            - name: Run tests
    #              run: npm run validate

    build_and_pub:
        # Если тесты были пройдены успешно
        needs: [run_tests]
        runs-on: [ubuntu-latest]
        env:
            LOGIN: ${{ secrets.DOCKER_LOGIN }}
            NAME: ${{ secrets.DOCKER_NAME }}
        steps:
            - name: Login to docker.io
                # Сначала мы логинимся в docker.io
              run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
                # Чекаутим код
            - uses: actions/checkout@v2
            - name: Build image
                # Собираем image и называем его так как указано в hub.docker т.е. login/repository:version
              run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
            - name: Push image to docker.io
                # Пушим образ в registry
              run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
